/** O'zbekcha UI matnlari */
export const uz = {
  common: {
    loading: 'Yuklanmoqda...',
    unlimited: 'Cheksiz',
    uzs: 'UZS',
    select: 'Tanlang…',
    export: 'Eksport',
    done: 'Tayyor',
    active: 'Faol',
    inactive: 'Nofaol',
    count: 'Soni',
    average: 'O\'rtacha',
    days7: '7 kun',
    signIn: 'Kirish',
    signOut: 'Chiqish',
    register: 'Ro\'yxatdan o\'tish',
    createAccount: 'Hisob yaratish',
    email: 'Elektron pochta',
    password: 'Parol',
    cancel: 'Bekor qilish',
    delete: 'O\'chirish',
    copy: 'Nusxalash',
    copied: 'Nusxalandi!',
    requestFailed: 'So\'rov bajarilmadi',
  },
  nav: {
    home: 'Bosh sahifa',
    campaigns: 'Kampaniyalar',
    businessAnalytics: 'Biznes analitikasi',
    agents: 'Agentlar',
    agentAnalytics: 'Agent analitikasi',
    chatDemo: 'Chat demo',
    newCampaign: 'Yangi kampaniya',
    registerAgent: 'Agent ro\'yxatdan o\'tkazish',
  },
  layout: {
    brand: 'Synaptic AI',
  },
  auth: {
    signInTitle: 'Kirish',
    signInSubtitle: 'Synaptic AI ga xush kelibsiz',
    loginFailed: 'Kirish muvaffaqiyatsiz',
    noAccount: 'Hisobingiz yo\'qmi?',
    registerNow: 'Ro\'yxatdan o\'ting',
    createTitle: 'Hisob yaratish',
    createSubtitle: 'AI reklama platformasiga qo\'shiling',
    registerFailed: 'Ro\'yxatdan o\'tish muvaffaqiyatsiz',
    hasAccount: 'Allaqachon hisobingiz bormi?',
    business: 'Biznes',
    aiAgent: 'AI agent',
  },
  home: {
    welcome: 'Reklama platformamizga xush kelibsiz',
    subtitle: 'Bizneslarni AI agentlar bilan bog\'lab, samaraliroq reklama qilamiz',
    forBusiness: 'Bizneslar uchun',
    forAgents: 'AI agentlar uchun',
    advertiseTitle: 'Aqlliroq reklama, kamroq xarajat',
    advertiseSub: 'AI suhbatlari orqali faol auditoriyaga yeting',
    advertiseBody:
      'Platformamiz har kuni minglab foydalanuvchilar bilan muloqot qiladigan AI agentlar orqali brendingizni tabiiy tarzda ko\'rsatadi.',
    contextual: 'Kontekstga mos',
    contextualDesc: 'Foydalanuvchi mavzuni muhokama qilganda reklama chiqadi',
    engagement: 'Yuqori jalb qilish',
    engagementDesc: 'AI agent mahsulotingizni suhbat ichida tavsiya qiladi',
    lowerCost: 'Arzonroq',
    lowerCostDesc: 'An\'anaviy reklamadan arzonroq bosish va konversiya',
    comparison: 'Platformalar taqqoslash',
    comparisonSub: 'An\'anaviy reklama bilan solishtiring',
    metric: 'Ko\'rsatkich',
    googleAds: 'Google Ads',
    ourPlatform: 'Bizning platforma',
    readyBusiness: 'Reklamangizni yangilashga tayyormisiz?',
    readyBusinessSub: 'Kam pulga yaxshi natija olayotgan minglab bizneslar qatoriga qo\'shiling',
    startAdvertising: 'Reklamani boshlash',
    viewDemo: 'Demo ko\'rish',
    monetizeTitle: 'AI agentingizdan daromad oling',
    monetizeSub: 'Foydalanuvchilarga foyda berib, daromad toping',
    monetizeBody:
      'Reklama API ni ulang. Suhbatga mos reklamalar ko\'rsating va har bosishdan daromad oling.',
    easyIntegration: 'Oson integratsiya',
    easyIntegrationDesc: 'Har qanday stack uchun REST API',
    contextualMatch: 'Kontekstli moslashtirish',
    contextualMatchDesc: 'Suhbat mazmuniga qarab reklama tanlanadi',
    transparentRevenue: 'Shaffof daromad',
    transparentRevenueDesc: 'Daromadni real vaqtda kuzating',
    howItWorks: 'Qanday ishlaydi',
    step1Title: 'API ni ulang',
    step1Desc: 'Backend dan yengil REST API chaqiring. 30 daqiqada sozlash mumkin.',
    step2Title: 'Reklama ko\'rsating',
    step2Desc: 'API mos reklamani qaytaradi. Qachon va qanday ko\'rsatishni siz belgilaysiz.',
    step3Title: 'Daromad oling',
    step3Desc: 'Har bosish va konversiyadan to\'lov. Minimal chegara yo\'q.',
    apiExample: 'Tezkor integratsiya namunasi',
    apiExampleDesc: 'Moslashtirish, ko\'rish va daromadni API o\'zi boshqaradi.',
    startEarning: 'Bugun daromad olishni boshlang',
    startEarningSub: 'Passiv daromad olayotgan AI agentlar tarmog\'iga qo\'shiling',
    getApiAccess: 'API kalit olish',
  },
  campaigns: {
    title: 'Kampaniyalar',
    subtitle: 'Kampaniya yarating va chatda ishlatiladigan kalit so\'zlarni belgilang.',
    newCampaign: 'Yangi kampaniya',
    createTitle: 'Yangi kampaniya yaratish',
    name: 'Kampaniya nomi',
    category: 'Kategoriya',
    subcategory: 'Pastki kategoriya',
    customCategory: 'O\'z kategoriyangiz nomi',
    tagline: 'Slogan',
    brandUrl: 'Brend havolasi',
    description: 'Tavsif',
    keywords: 'Kalit so\'zlar',
    keywordsHint: 'Vergul bilan ajrating — foydalanuvchi chatda aytishi mumkin.',
    nicheKeywords: 'Niche kalit so\'zlar (ixtiyoriy)',
    cpc: 'Bosish narxi (UZS)',
    cpa: 'CPA %',
    balance: 'Kampaniya balansi (UZS)',
    balanceHint: 'Har bosishda CPC ushbu balansdan ayiriladi.',
    balancePlaceholder: 'masalan 500000',
    creating: 'Yaratilmoqda...',
    create: 'Kampaniyani yaratish',
    deleteConfirm: 'Kampaniyani o\'chirish',
    deleteFailed: 'Kampaniyani o\'chirib bo\'lmadi',
    createFailed: 'Kampaniyani yaratib bo\'lmadi',
    noCampaigns: 'Kampaniyalar topilmadi. Boshlash uchun birinchi kampaniyani yarating!',
    colName: 'Nom',
    colCategory: 'Kategoriya',
    colBalance: 'Qolgan balans',
    colUsed: 'Sarflangan',
    colActions: 'Amallar',
  },
  balance: {
    mainLabel: 'Asosiy balans (kampaniya balanslari yig\'indisi)',
    mainHint: (n: number) =>
      `${n} ta kampaniya — bosishlar har bir kampaniya balansini kamaytiradi`,
  },
  businessAnalytics: {
    title: 'Biznes analitikasi',
    campaignTitle: (name: string) => `${name} — analitika`,
    subtitle: 'Bosishlar va reklama xarajatlarini kuzating',
    showing: (name: string) => `Ko\'rsatilmoqda: ${name}`,
    noCampaigns: 'Kampaniyalar topilmadi',
    noCampaignsSub: 'Analitikani ko\'rish uchun birinchi kampaniyani yarating',
    createCampaign: 'Kampaniya yaratish',
    totalClicks: 'Jami bosishlar',
    costPerClick: 'Bosish narxi (UZS)',
    balanceLeft: 'Qolgan balans',
    thisCampaign: 'Ushbu kampaniya',
    usedSoFar: (n: string) => `Sarflangan: ${n} UZS`,
    ctr: 'Bosishlar ulushi (CTR)',
    dailyClicks: 'Kunlik bosishlar',
    dailyClicksSub: 'Kun bo\'yicha havolalaringizga bosishlar soni',
    funnel: 'Konversiya voronkasi',
    funnelSub: 'Harakat turi bo\'yicha natijalar',
    actionType: 'Harakat turi',
    totalEvents: 'Jami hodisalar',
    conversions: 'Konversiyalar',
    conversionRate: 'Konversiya %',
    productView: 'Mahsulot ko\'rildi',
    addToCart: 'Savatga qo\'shildi',
    purchase: 'Xarid',
  },
  agents: {
    title: 'AI agentlar',
    subtitle: 'Ro\'yxatdan o\'tgan agentlar va integratsiyalar',
    register: 'Agent ro\'yxatdan o\'tkazish',
    registerTitle: 'Yangi AI agent',
    registerSuccess: 'Agent muvaffaqiyatli ro\'yxatdan o\'tdi. API kalitni nusxalang — keyin ko\'rsatilmaydi.',
    copyApiKey: 'API kalitni nusxalash',
    username: 'Agent foydalanuvchi nomi',
    usernameHint: 'Kuzatuv havolalari va analitikada ishlatiladi',
    ownerEmail: 'Egasi emaili',
    generating: 'Yaratilmoqda...',
    generateKey: 'API kalit yaratish',
    registerFailed: 'Agentni ro\'yxatdan o\'tkazib bo\'lmadi',
    colUsername: 'Agent ID (username)',
    colOwner: 'Egasi emaili',
    colStatus: 'Holat',
    colRequests: 'Jami so\'rovlar',
    colClicks: 'Yaratilgan bosishlar',
    lastSeen: 'Oxirgi faollik',
    empty: 'Hali agentlar ro\'yxatdan o\'tmagan.',
  },
  agentAnalytics: {
    title: 'Agent analitikasi',
    agentTitle: (name: string) => `${name} — analitikasi`,
    subtitle: 'AI agent monetizatsiyasi va trafik',
    showing: (name: string) => `Ko\'rsatilmoqda: ${name}`,
    download: 'Ma\'lumotni yuklab olish',
    noAgents: 'Agentlar topilmadi',
    noAgentsSub: 'Analitikani ko\'rish uchun birinchi agentni ro\'yxatdan o\'tkazing',
    registerAgent: 'Agent ro\'yxatdan o\'tkazish',
    revenue: 'Jami daromad',
    impressions: 'Jami ko\'rishlar',
    clicks: 'Jami bosishlar',
    ctr: 'Bosishlar ulushi',
    revenueChart: 'Daromad ko\'rinishi',
    revenueChartSub: 'Bosishlar asosida taxminiy daromad',
    impressionsChart: 'Jami ko\'rishlar',
    impressionsChartSub: 'Reklamani ko\'rgan foydalanuvchilar',
  },
  chat: {
    botName: 'Synaptic Demo Bot',
    online: 'onlayn',
    typing: 'yozmoqda…',
    greeting: 'Assalomu alaykum! Sizga qanday yordam bera olaman?',
    placeholder: 'Xabar',
    send: 'Yuborish',
    fallback: "Savolingiz bo'yicha yordam bera olaman. Biroz batafsil yozsangiz, aniqroq javob beraman.",
    details: "Batafsil ma'lumot",
    sponsored: '[REKLAMA]',
  },
  notFound: {
    title: '404',
    message: 'Sahifa topilmadi',
    agentAnalytics: 'Agent analitikasi',
    businessAnalytics: 'Biznes analitikasi',
  },
} as const;

export const dateLocale = 'uz-UZ';
